# Generated by Django 5.0.2 on 2024-02-13 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_model_alter_news_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='News.model'),
        ),
    ]
