# Generated by Django 5.0.2 on 2024-02-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0007_alter_news_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created',
        ),
    ]
