# Generated by Django 5.0.2 on 2024-02-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='User.jpg', upload_to='user_photo'),
        ),
    ]
